# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c960a293989fb070510e8e30ba608c4d199932415ace036f3d0c2097ed57b77b83a4ecb58c7220cafab6a210594260b5c9d38bc8d5c3ff3851c91d007d56ffcb

test:
  secret_key_base: b77930af9b576b72b87e88a71c0aef292dbb3a45d501a8a8c320c06fd7cbad0376e348be145648f371c1b039cb1db830dc1d69fd2a876875d901ffef19cfe32b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
