# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db59d27dced3a399192852fbe319417e186e6447a81ec6fdfff22f32e186c219aed5e8fd6e26023b73782c8f9b6510403f3a24470bf70a583ddada203e9a400

test:
  secret_key_base: 37de5ed52739a57906a255f238d9b32dc9177858290cec96ca4c6e1365019d0502ce31f1fbc186989b9c13e84415245ac8b667b091ba1bcbd52b624724acd29c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
